# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 998533df036166b5a35d77c4d4ef460297f3eeac5b19d5e9d56f77051488deca23a468807af9ec7d44b53b0d783f2a2b8a4e7eb73dd45028c0f0f6d749e0817c

test:
  secret_key_base: 5be4b86af3618364be85345a35e2dd544b7f35f1273f05f55525d708b4d8dfbca50b45aa6ae4b8d89c7160300c21bec8ad9767d54c16e56c337d78ba2ef31c0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
